services:
  broker-d:
    build:
      context: .
      dockerfile: Dockerfile.broker
    environment:
      BROKER_ID: "D"
      PORTA: "5004"
      PEERS: "172.16.103.2:5001,172.16.103.3:5002,172.16.103.4:5003,172.16.103.5:5005"
    ports:
      - "5004:5004"

  broker-e:
    build:
      context: .
      dockerfile: Dockerfile.broker
    environment:
      BROKER_ID: "E"
      PORTA: "5005"
      PEERS: "172.16.103.2:5001,172.16.103.3:5002,172.16.103.4:5003,172.16.103.5:5004"
    ports:
      - "5005:5005"

  sensor-d:
    build:
      context: .
      dockerfile: Dockerfile.sensor
    environment:
      SETOR_ID: "D"
      BROKER_ADDR: "172.16.103.5:5004"
      INTERVALO_MS: "18000"
    depends_on:
      - broker-d

  sensor-e:
    build:
      context: .
      dockerfile: Dockerfile.sensor
    environment:
      SETOR_ID: "E"
      BROKER_ADDR: "172.16.103.5:5005"
      INTERVALO_MS: "16000"
    depends_on:
      - broker-e

  drone-4:
    build:
      context: .
      dockerfile: Dockerfile.drone
    environment:
      DRONE_ID: "drone-4"
      PORTA: "6004"
      ADDR: "172.16.103.5"
      BROKERS: "172.16.103.2:5001,172.16.103.3:5002,172.16.103.4:5003,172.16.103.5:5004,172.16.103.5:5005"
    ports:
      - "6004:6004"