services:
  broker-c:
    build: ./broker
    environment:
      BROKER_ID: "C"
      PORTA: "5003"
      PEERS: "172.16.103.2:5001,172.16.103.3:5002"
    ports: ["5003:5003"]

  sensor-e:
    build: ./sensor
    environment:
      SETOR_ID: "E"
      BROKER_ADDR: "172.16.103.4:5003"
      INTERVALO_MS: "3000"
    depends_on: [broker-c]

  sensor-f:
    build: ./sensor
    environment:
      SETOR_ID: "F"
      BROKER_ADDR: "172.16.103.4:5003"
      INTERVALO_MS: "4500"
    depends_on: [broker-c]

  drone-3:
    build: ./drone
    environment:
      DRONE_ID: "drone-3"
      PORTA: "6003"
      ADDR: "172.16.103.4"
      BROKERS: "172.16.103.2:5001,172.16.103.3:5002,172.16.103.4:5003"
    ports: ["6003:6003"]