services:
  broker-b:
    build:
      context: .
      dockerfile: Dockerfile.broker
    environment:
      BROKER_ID: "B"
      PORTA: "5002"
      PEERS: "172.16.103.2:5001,172.16.103.4:5003,172.16.103.5:5004,172.16.103.5:5005"
    ports:
      - "5002:5002"

  sensor-b:
    build:
      context: .
      dockerfile: Dockerfile.sensor
    environment:
      SETOR_ID: "B"
      BROKER_ADDR: "172.16.103.3:5002"
      INTERVALO_MS: "15000"
    depends_on:
      - broker-b

  drone-2:
    build:
      context: .
      dockerfile: Dockerfile.drone
    environment:
      DRONE_ID: "drone-2"
      PORTA: "6002"
      ADDR: "172.16.103.3"
      BROKERS: "172.16.103.2:5001,172.16.103.3:5002,172.16.103.4:5003,172.16.103.5:5004,172.16.103.5:5005"
    ports:
      - "6002:6002"