services:
  broker-c:
    build:
      context: .
      dockerfile: Dockerfile.broker
    environment:
      BROKER_ID: "C"
      PORTA: "5003"
      PEERS: "172.16.103.2:5001,172.16.103.3:5002,172.16.103.5:5004,172.16.103.5:5005"
    ports:
      - "5003:5003"

  sensor-c:
    build:
      context: .
      dockerfile: Dockerfile.sensor
    environment:
      SETOR_ID: "C"
      BROKER_ADDR: "172.16.103.4:5003"
      INTERVALO_MS: "14000"
    depends_on:
      - broker-c

  drone-3:
    build:
      context: .
      dockerfile: Dockerfile.drone
    environment:
      DRONE_ID: "drone-3"
      PORTA: "6003"
      ADDR: "172.16.103.4"
      BROKERS: "172.16.103.2:5001,172.16.103.3:5002,172.16.103.4:5003,172.16.103.5:5004,172.16.103.5:5005"
    ports:
      - "6003:6003"